Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> def prime_generator(n):
...   """Generator function that generates all the prime numbers less than n."""
...   for i in range(2, n + 1):
...     is_prime = True
...     for j in range(2, i):
...       if i % j == 0:
...         is_prime = False
...         break
...     if is_prime:
...       yield i
... 
... 
... #@log
... def prime_iterator(n):
...   """Iterator object that iterates over the prime numbers generated by prime_generator."""
...   for prime in prime_generator(n):
...     yield prime
... 
... 
... def log(func):
...   """Decorator that adds a logging function to the decorated function."""
...   def wrapper(*args, **kwargs):
...     print(func.name, args, kwargs)
...     return func(*args, **kwargs)
...   return wrapper
... 
... 
... if _name_ == "_main_":
...   for prime in prime_iterator(100):
